apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - acm-operator.yaml
  - acm-crd-mch.yaml
  - acm-namespaces.yaml
  - acm-managed-clusterset-binding.yaml
#  - acm-agent-service-mirror-config.yaml
  - installplan-approver-acm-sub
  - installplan-approver-talm-sub
  - installplan-approver-multicluster-engine