apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- gitops-operator.yaml
- gitops-rbac.yaml
- git-secrets.yaml
- crb-manageclusterset-admin-gitops-sa.yaml
- installplan-approver
