##TODO this has a dependency on the ACM application. So we might
#have to merge the root-application into the ACM application with a sync-wave on it.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: placements
  namespace: ztp-gitops
spec:
  destination:
    namespace: ztp-gitops
    server: https://kubernetes.default.svc
  project: policy-appproject
  source:
    path: placements
    repoURL: https://repourl/XXX-policies # value will be automatically updated based on gitops.properties
    targetRevision: main
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    automated:
      prune: true
      selfHeal: true