apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: policies-access-control
  namespace: ztp-gitops
spec:
  destination:
    namespace: ztp-gitops
    server: https://kubernetes.default.svc
  project: policy-appproject
  source:
    path: policygen/AC-Access-Control
    repoURL: https://repourl/XXX-policies # value will be automatically updated based on gitops.properties
    targetRevision: main
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    automated:
      prune: false
      selfHeal: false