ztp_policy_appproject_url=https://github.com/federated-fleet-forge/example-ocp-policies
ztp_appproject_url=https://github.com/federated-fleet-forge/example-ocp-policies
policies_repo_secret_git_url=https://github.com/federated-fleet-forge/example-ocp-policies
policies_url=https://github.com/federated-fleet-forge/example-ocp-policies
cgu_url=https://github.com/federated-fleet-forge/example-ocp-policies
policies_configuration_management_url=https://github.com/federated-fleet-forge/example-ocp-policies
placements_url=https://github.com/federated-fleet-forge/example-ocp-policies
app_policies_configuration_management_url=https://github.com/federated-fleet-forge/example-ocp-policies
app_policies_security_and_communication_url=https://github.com/federated-fleet-forge/example-ocp-policies
siteconfig_repo_secret_git_url=https://github.com/federated-fleet-forge/example-ocp-ztp
cluster_info_policies_url=https://github.com/federated-fleet-forge/example-ocp-ztp
target.revision=networklab-workshop
ztp_target.revision=networklab-workshop
