apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ztp-namespace.yaml
  - gitops-cluster-rolebinding.yaml
  - gitops-rbac.yaml
  - ztp-gitops-instance.yaml
  - clusters-apps/
  - policies-apps/
  - acm-apps/

configMapGenerator:
- name: config
  envs:
  - gitops.properties

replacements:
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.ztp_image
  targets:
  - select:
      kind: ArgoCD
      name: ztp-gitops
    fieldPaths:
    - spec.repo.initContainers.0.image
- source:
    kind: ConfigMap
    name: config
    fieldPath: data.policygen_image
  targets:
  - select:
      kind: ArgoCD
      name: ztp-gitops
    fieldPaths:
    - spec.repo.initContainers.1.image

