# CHANGE: update to your fork URLs if not using the upstream repos
gitops_base_repo_secret_git_url=https://github.com/federated-fleet-forge/example-ocp-gitops-base
policies_repo_secret_git_url=https://github.com/federated-fleet-forge/example-ocp-policies
siteconfig_repo_secret_git_url=https://github.com/federated-fleet-forge/example-ocp-ztp
target.revision=networklab-workshop
